spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    database: "h2"
    show-sql: true
    hibernate:
      ddl-auto: "create-drop"
  h2:
    console:
      enabled: true
  datasource:
    type: "com.zaxxer.hikari.HikariDataSource"
    platform: "h2"

logging:
  level:
    org:
      hibernate:
        SQL: "DEBUG"
        
batch:
  folders:
    clients: "/clients/*"
  chunk:
    size: 10
  linestoskip: 1
  delimiter: ";"