spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    database: "h2"
    show-sql: false
    hibernate:
      ddl-auto: "create-drop"

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    
  h2:
    console:
      enabled: true
      path: /console
        
batch:
  folders:
    clients: "/clients/*"
  chunk:
    size: 10
  linestoskip: 1
  delimiter: ";"